[general]
live_config_reload = true

[font]
size = 11.6

[font.normal]
# family = "Maple Mono NF"
family = "Maple Mono"
style = "Light"

[window]
opacity = 0.8
dimensions = { columns = 120, lines = 30 }

[cursor]
style = "Beam"

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "F11", action = "ToggleFullscreen" },
]

[env]
SHELL = "/usr/bin/fish"

# -----------------------------------------------------------------------------
# TokyoNight Alacritty Colors
# Theme: Tokyo Night Moon
# Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/alacritty/tokyonight_moon.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#222436'
foreground = '#c8d3f5'

#[colors.cursor]
#cursor = '#c8d3f5'
#text = '#222436'

# Normal colors
[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

# Bright colors
[colors.bright]
black = '#444a73'
red = '#ff8d94'
green = '#c7fb6d'
yellow = '#ffd8ab'
blue = '#9ab8ff'
magenta = '#caabff'
cyan = '#b2ebff'
white = '#c8d3f5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'

# Source: https://github.com/alacritty/alacritty/issues/5246#issuecomment-2765912471
[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
# command       = "open" # On macOS
# command       = { program = "cmd", args = [ "/c", "start",  "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
mouse.mods = "Control"                                                                                                                                     # "Control|Shift" is my preference
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|go‐pher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
